using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;

namespace Veneer;

public class Transpiler
{
    private readonly List<Tokens.Token> _tokens;
    private int _index = 0;
    private string _build;
    private Dictionary<string, LanguageConfig.Config> _configs;
    private List<Tokens.Token> toothModifiers = new();

    // Fully-parsed user-defined classes, collected separately from the
    // auto-generated Program wrapper so they can be emitted as top-level
    // siblings instead of being folded into (and overridden by) it.
    private readonly List<string> _userClasses = new();

    // Modifier keywords that can legally precede a class or function declaration.
    private static readonly HashSet<Tokens.TokenType> ModifierTokens = new()
    {
        Tokens.TokenType.Public, Tokens.TokenType.Private, Tokens.TokenType.Protected, Tokens.TokenType.Internal,
        Tokens.TokenType.Static, Tokens.TokenType.ReadOnly, Tokens.TokenType.Const,
        Tokens.TokenType.Async, Tokens.TokenType.Virtual, Tokens.TokenType.Override, Tokens.TokenType.Sealed
    };

    public Transpiler(List<Tokens.Token> tokens, string build, Dictionary<string, LanguageConfig.Config> configs)
    {
        _tokens = tokens;
        _build = build;
        _configs = configs;
    }

    // Helper to look ahead without consuming
    private Tokens.Token Peek(int offset = 0)
    {
        if (_index + offset >= _tokens.Count) 
            return new Tokens.Token(Tokens.TokenType.EndOfFile, "");
        return _tokens[_index + offset];
    }

    // Guard & consume an expected token type
    private Tokens.Token Consume(Tokens.TokenType type, string errorMessage)
    {
        var token = Peek();
        if (token.Type != type) 
            throw new Exception($"[Transpile Error] {errorMessage} Found '{token.Value}' instead at token position {_index}.");
        _index++;
        return token;
    }

    public string Transpile()
    {
        string imports = _configs.ContainsKey("CSHARP") ? _configs["CSHARP"].imports : "";
        
        var sb = new StringBuilder();
        
        // Phase 4 Blueprint: Generate a high-performance C# template class
        sb.AppendLine("//---------------------------------------------------------");
        sb.AppendLine("// <auto-generated> Transpiled from Veneer Source </auto-generated>");
        sb.AppendLine("//---------------------------------------------------------");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine(imports);
        sb.AppendLine("namespace VeneerRuntime;");
        sb.AppendLine();

        // Top-level func/tooth constructs still get collected into the
        // auto-generated Program wrapper below. User-defined classes are
        // parsed out separately (see ParseClass) into _userClasses so this
        // wrapper never nests or overrides them.
        var programBody = new StringBuilder();
        while (Peek().Type != Tokens.TokenType.EndOfFile)
        {
            programBody.Append(ParseTopLevelStatement());
        }

        // Emit user-defined classes as their own top-level types —
        // siblings of Program, never children of it.
        foreach (var userClass in _userClasses)
        {
            sb.AppendLine(userClass);
            sb.AppendLine();
        }

        // Only emit the auto-generated Program wrapper if there's actual
        // top-level func/tooth content for it to hold. If the user's source
        // is fully organized into their own class(es), there's nothing left
        // that needs auto-wrapping.
        if (programBody.ToString().Trim().Length > 0)
        {
            sb.AppendLine("public static class Program");
            sb.AppendLine("{");
            sb.Append(programBody);
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private string ParseTopLevelStatement()
    {
        var token = Peek();
        
        if (token.Type == Tokens.TokenType.Function)
        {
            return ParseFunction();
        }
        if (token.Type == Tokens.TokenType.Tooth)
        {
            return ParseTooth();
        }
        if (IsClassDeclarationAhead())
        {
            // Parse the user's class as one complete unit and stash it in
            // _userClasses instead of letting it fall through to raw token
            // emission — that's what used to let it get folded into, and
            // effectively overridden by, the auto-generated Program wrapper.
            _userClasses.Add(ParseClass());
            return string.Empty;
        }

        // Allow other global expressions to fall back gracefully
        _index++;
        if (token.Type == Tokens.TokenType.ToothModifier)
        {
            toothModifiers.Add(token);
            return string.Empty;    
        }
        return EmitTokenFormatting(token);
    }

    // Looks ahead past any leading modifiers (public, static, sealed, etc.)
    // to check whether a class declaration begins at the current position.
    private bool IsClassDeclarationAhead()
    {
        int offset = 0;
        while (ModifierTokens.Contains(Peek(offset).Type))
        {
            offset++;
        }
        return Peek(offset).Type == Tokens.TokenType.Class;
    }

    // Translates: [MODIFIERS] class [IDENTIFIER] [: BASE, ...] { ... }
    // Parsed as one coherent unit (instead of falling through to raw,
    // token-by-token emission) so it can be returned to the caller and
    // placed as its own top-level class rather than folded into the
    // auto-generated Program class.
    private string ParseClass()
    {
        var sb = new StringBuilder();

        while (ModifierTokens.Contains(Peek().Type))
        {
            sb.Append(Peek().Value + " ");
            _index++;
        }

        Consume(Tokens.TokenType.Class, "Expected 'class' keyword.");
        sb.Append("class ");

        var nameTok = Consume(Tokens.TokenType.Identifier, "Expected identifier for class name.");
        sb.Append(nameTok.Value);

        // Optional base class / interface list: class Foo : Base, IBar
        if (Peek().Type == Tokens.TokenType.Colon)
        {
            _index++;
            sb.Append(" : ");
            var parts = new List<string>();
            while (Peek().Type != Tokens.TokenType.LeftBrace && Peek().Type != Tokens.TokenType.EndOfFile)
            {
                parts.Add(Peek().Type == Tokens.TokenType.Comma ? ", " : Peek().Value);
                _index++;
            }
            sb.Append(string.Join("", parts));
        }

        sb.Append('\n');
        sb.Append(ParseClassBody());

        return sb.ToString();
    }

    // Parses a class body using the same construct rules as the top level
    // (functions, tooth blocks, nested classes, raw member fallback for
    // things like fields/constructors), but stops at the class's own
    // closing brace instead of end-of-file.
    private string ParseClassBody()
    {
        Consume(Tokens.TokenType.LeftBrace, "Expected '{' opening class body.");
        var sb = new StringBuilder("{\n");
        int braceScope = 1;

        while (braceScope > 0 && Peek().Type != Tokens.TokenType.EndOfFile)
        {
            var token = Peek();

            if (token.Type == Tokens.TokenType.Function)
            {
                sb.Append(ParseFunction());
                continue;
            }
            if (token.Type == Tokens.TokenType.Tooth)
            {
                sb.Append(ParseTooth());
                continue;
            }
            if (IsClassDeclarationAhead())
            {
                // A genuine nested class authored by the user — nest it
                // inline. This is not the auto-Program-wrapper problem;
                // intentional nesting like this should be preserved.
                sb.Append(ParseClass());
                continue;
            }

            if (token.Type == Tokens.TokenType.LeftBrace) braceScope++;
            if (token.Type == Tokens.TokenType.RightBrace) braceScope--;

            _index++;

            if (braceScope == 0)
            {
                sb.AppendLine("}");
                break;
            }

            if (token.Type == Tokens.TokenType.ToothModifier)
            {
                toothModifiers.Add(token);
                continue;
            }

            sb.Append(EmitTokenFormatting(token));
        }

        return sb.ToString();
    }
    
    // Parsing for return type
    private string ParseReturnType()
    {
        var sb = new StringBuilder();
        while (Peek().Type != Tokens.TokenType.GreaterThan && Peek().Type != Tokens.TokenType.EndOfFile)
        {
            sb.Append(Peek().Value);
            _index++;
        }
        return sb.ToString();
    }

    // Translates: func<[RETURN_TYPE]> [IDENTIFIER] ([ARGS]) { ... }
    private string ParseFunction()
    {
        Consume(Tokens.TokenType.Function, "Expected 'func' keyword.");
        Consume(Tokens.TokenType.LessThan, "Expected '<' following 'func'.");
        
        string returnType = ParseReturnType();
        
        Consume(Tokens.TokenType.GreaterThan, "Expected '>' closing return type.");
        
        var nameTok = Consume(Tokens.TokenType.Identifier, "Expected identifier for function name.");
        string funcName = nameTok.Value;

        // Auto-map lower-case 'main' to C#'s entry point format
        if (funcName == "main") funcName = "Main";

        Consume(Tokens.TokenType.LeftParen, "Expected '(' after function identifier.");
        
        var paramsSb = new StringBuilder();
        while (Peek().Type != Tokens.TokenType.RightParen && Peek().Type != Tokens.TokenType.EndOfFile)
        {
            paramsSb.Append(Peek().Value + " ");
            _index++;
        }
        Consume(Tokens.TokenType.RightParen, "Expected ')' closing parameters.");

        // Grab internal function block execution loops
        string blockBody = ParseBlock();

        return $"{returnType} {funcName}({paramsSb.ToString().Trim()})\n\t{blockBody}\n";
    }

    // Parse C# function notation into a function of foreign language for compiling
    private string CreateForeignFunction(string parameters, string language, string body, string returnType, string functionName)
    {
        // Local helper to parse structured variable/type information out of individual token streams
        var parseParamFromTokens = (List<Tokens.Token> toks) =>
        {
            string bType = "void";
            int rank = 0;
            string name = "";
            
            if (toks.Count > 0)
            {
                name = toks.Last().Value;
                var typeToks = toks.Take(toks.Count - 1).ToList();
                if (typeToks.Count > 0)
                {
                    bType = typeToks[0].Value;
                    bool isArray = typeToks.Any(t => t.Type == Tokens.TokenType.LeftBracket);
                    if (isArray)
                    {
                        int commaCount = typeToks.Count(t => t.Type == Tokens.TokenType.Comma);
                        int bracketCount = typeToks.Count(t => t.Type == Tokens.TokenType.LeftBracket);
                        rank = Math.Max(bracketCount, commaCount + 1);
                    }
                }
            }
            return (BaseType: bType, ArrayRank: rank, Name: name);
        };

        // Mapping layer matching Veneer type syntax structures to your target runtime systems
        var mapTypeToLanguage = (string baseType, int rank, string lang) =>
        {
            switch (lang)
            {
                case "CSHARP":
                case "JAVA":
                    string csBase = baseType switch {
                        "int" => "int",
                        "float" => "float",
                        "bool" => lang == "JAVA" ? "boolean" : "bool",
                        "char" => "char",
                        "string" => lang == "JAVA" ? "String" : "string",
                        "void" => "void",
                        _ => baseType
                    };
                    if (rank == 0) return csBase;
                    return lang == "CSHARP" 
                        ? csBase + "[" + new string(',', rank - 1) + "]" 
                        : csBase + string.Concat(System.Linq.Enumerable.Repeat("[]", rank));

                case "TYPESCRIPT":
                    string tsBase = baseType switch {
                        "int" or "float" => "number",
                        "bool" => "boolean",
                        "char" or "string" => "string",
                        "void" => "void",
                        _ => baseType
                    };
                    if (rank == 0) return tsBase;
                    return tsBase + string.Concat(System.Linq.Enumerable.Repeat("[]", rank));

                case "C":
                case "C++":
                case "CPP":
                    string cBase = baseType switch {
                        "int" => "int",
                        "float" => "float",
                        "bool" => "bool",
                        "char" => "char",
                        "string" => lang == "C" ? "const char*" : "std::string",
                        "void" => "void",
                        _ => baseType
                    };
                    if (rank == 0) return cBase;
                    return cBase + new string('*', rank);

                case "RUST":
                    if (baseType == "void") return "()";
                    string rustBase = baseType switch {
                        "int" => "i32",
                        "float" => "f32",
                        "bool" => "bool",
                        "char" => "char",
                        "string" => "&str",
                        _ => baseType
                    };
                    if (rank == 0) return rustBase;
                    string rustType = rustBase;
                    for (int i = 0; i < rank; i++) rustType = $"&[{rustType}]";
                    return rustType;

                case "GO":
                    if (baseType == "void") return "";
                    string goBase = baseType switch {
                        "int" => "int",
                        "float" => "float64",
                        "bool" => "bool",
                        "char" => "rune",
                        "string" => "string",
                        _ => baseType
                    };
                    if (rank == 0) return goBase;
                    return string.Concat(System.Linq.Enumerable.Repeat("[]", rank)) + goBase;

                default:
                    return "";
            }
        };

        // Clean structural target name rules
        string langUpper = language.ToUpper().Trim().Replace("\"", "");
        
        // 1. Process and extract properties of the Return Type string
        var returnToks = Lexer.LexText(returnType).Where(t => t.Type != Tokens.TokenType.EndOfFile).ToList();
        string retBase = returnToks.Count > 0 ? returnToks[0].Value : "void";
        int retRank = 0;
        if (returnToks.Any(t => t.Type == Tokens.TokenType.LeftBracket))
        {
            int commaCount = returnToks.Count(t => t.Type == Tokens.TokenType.Comma);
            int bracketCount = returnToks.Count(t => t.Type == Tokens.TokenType.LeftBracket);
            retRank = Math.Max(bracketCount, commaCount + 1);
        }

        // 2. Loop parameters via Lexer token boundaries to safely bypass nested dimensional arrays
        var paramTokens = Lexer.LexText(parameters).Where(t => t.Type != Tokens.TokenType.EndOfFile).ToList();
        var parsedParams = new List<(string BaseType, int ArrayRank, string Name)>();
        var currentTokens = new List<Tokens.Token>();
        int bracketScope = 0;

        foreach (var tok in paramTokens)
        {
            if (tok.Type == Tokens.TokenType.LeftBracket) bracketScope++;
            if (tok.Type == Tokens.TokenType.RightBracket) bracketScope--;

            if (tok.Type == Tokens.TokenType.Comma && bracketScope == 0)
            {
                if (currentTokens.Count > 0)
                {
                    parsedParams.Add(parseParamFromTokens(currentTokens));
                    currentTokens.Clear();
                }
            }
            else
            {
                currentTokens.Add(tok);
            }
        }
        if (currentTokens.Count > 0)
        {
            parsedParams.Add(parseParamFromTokens(currentTokens));
        }

        // 3. Rebuild and map parameters array structures matching specific language syntaxes
        var argStrings = new List<string>();
        foreach (var p in parsedParams)
        {
            string typeStr = mapTypeToLanguage(p.BaseType, p.ArrayRank, langUpper);
            switch (langUpper)
            {
                case "PYTHON":
                case "JAVASCRIPT":
                    argStrings.Add(p.Name);
                    break;
                case "TYPESCRIPT":
                    argStrings.Add($"{p.Name}: {typeStr}");
                    break;
                case "CSHARP":
                case "JAVA":
                case "C":
                case "C++":
                case "CPP":
                    argStrings.Add($"{typeStr} {p.Name}");
                    break;
                case "RUST":
                    argStrings.Add($"{p.Name}: {typeStr}");
                    break;
                case "GO":
                    argStrings.Add($"{p.Name} {typeStr}");
                    break;
            }
        }

        string formattedArgs = string.Join(", ", argStrings);
        string retTypeStr = mapTypeToLanguage(retBase, retRank, langUpper);
        string osSpecificLeadingText = "";
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            osSpecificLeadingText = "__delspec(dllexport)";
        }

        // 4. Output final code block syntax skeleton templates
        switch (langUpper)
        {
            case "PYTHON":
                return $"def {functionName}({formattedArgs}):\n{body}";
                
            case "JAVASCRIPT":
                return $"function {functionName}({formattedArgs}) {{\n{body}\n}}";
                
            case "TYPESCRIPT":
                return $"function {functionName}({formattedArgs}): {retTypeStr} {{\n{body}\n}}";
                
            case "CSHARP":
                return $"{retTypeStr} {functionName}({formattedArgs}) {{\n{body}\n}}";
                
            case "JAVA":
                return $"@CEntryPoint(name = \"{functionName}X\")\npublic static {retTypeStr} {functionName}(IsolateThread thread, {formattedArgs}) {{\n{body}\n}}";
                
            case "C":
                return $"{osSpecificLeadingText} {retTypeStr} {functionName}({formattedArgs}) {{\n{body}\n}}";
            case "CPP":
            case "C++":
                return $"extern \"C\" {{\n {osSpecificLeadingText} {retTypeStr} {functionName}({formattedArgs}) {{\n{body}\n}}\n}}";
            case "RUST":
                string rustRet = retBase == "void" ? "" : $" -> {retTypeStr}";
                return $"#[no_mangle]\nfn {functionName}({formattedArgs}){rustRet} {{\n{body}\n}}";
                
            case "GO":
                string goRet = retBase == "void" ? "" : $" {retTypeStr}";
                return $"//export {functionName}\nfunc {functionName}({formattedArgs}){goRet} {{\n{body}\n}}";
                
            default:
                return string.Empty;
        }
    }

    // Generate library file for languages that support DLLImport utility of c#
    private string CompileFunction(string function, string language, string cWrapper = "", string functionName = "")
    {
        LanguageConfig.Config config = _configs.ContainsKey(language) 
            ? _configs[language] 
            : new LanguageConfig.Config("", "");
        string imports = config.imports;
        
        string name = Guid.NewGuid().ToString();
        switch (language)
        {
            case "C++":
            case "CPP":
            case "C":
                string cImports = """
                                 #include <stdio.h>
                                 #include <stdlib.h>
                                 #include <stdbool.h>
                                 """;
                string cppImports = """
                                    #include <iostream>
                                    #include <string>
                                    """;
                string finalImports = language == "C" ?  cImports : cppImports;
                string fileType = language == "C" ? ".c" : ".cpp";
                
                string cFile = Path.Join(_build, $"{name}{fileType}");
                File.WriteAllText(cFile, $"{finalImports}\n{imports}\n{function}");
                string cOutputFile = Path.Join(_build, $"{name}");

                string arguments = "";
                if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                {
                    cOutputFile += ".dll";
                    arguments = $"-shared -o {cOutputFile} {cFile}";
                }
                else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                {
                    cOutputFile += ".so";
                    arguments = $"-shared -fPIC -o {cOutputFile} {cFile}";
                }
                else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                {
                    cOutputFile += ".dylib";
                    arguments = $"-dynamiclib -o {cOutputFile} {cFile}";
                }

                string compiler = language == "C" ? "gcc" : "g++";
                ProcessStartInfo cStartInfo = new ProcessStartInfo
                {
                    FileName = compiler,
                    Arguments = arguments,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                using (Process cProcess = Process.Start(cStartInfo))
                {
                    string cOutput = cProcess.StandardOutput.ReadToEnd();
                    string cError = cProcess.StandardError.ReadToEnd();
                    
                    Console.WriteLine(cOutput);
                    
                    cProcess.WaitForExit();

                    if (cProcess.ExitCode != 0)
                    {
                        Console.WriteLine($"Error: {cError}");
                    }
                }
                
                File.Delete(cFile);
                File.Delete(Path.Join(_build, $"{name}.o"));
                
                return cOutputFile;
            case "RUST":
                string rustFile = Path.Join(_build, $"{name}.rs");
                File.WriteAllText($"{imports}\n{rustFile}", function);
                string rustOutputFile = Path.Join(_build, $"{name}");
                if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                {
                    rustOutputFile = $"{rustOutputFile}lib.dll";
                }
                else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                {
                    rustOutputFile = $"{rustOutputFile}lib.so";
                }
                else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                {
                    rustOutputFile = $"{rustOutputFile}lib.dylib";
                }

                ProcessStartInfo rustInfo = new ProcessStartInfo
                {
                    FileName = "rustc",
                    Arguments = $"--crate-type=cdylib {rustFile} -o {rustOutputFile}",
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                using (Process rustProcess = Process.Start(rustInfo))
                {
                    string rustOutput = rustProcess.StandardOutput.ReadToEnd();
                    string rustError = rustProcess.StandardError.ReadToEnd();
                    
                    Console.WriteLine(rustOutput);
                    
                    rustProcess.WaitForExit();

                    if (rustProcess.ExitCode != 0)
                    {
                        Console.WriteLine($"Error: {rustError}");
                    }
                }
                
                File.Delete(rustFile);
                
                return rustOutputFile;
            case "GO":
                string goFile = Path.Join(_build, $"{name}.go");
                string goImports = """
                                   package main
                                   import "C"
                                   """;
                string goMainFunction = "func main() {}";
                File.WriteAllText(goFile, $"{goImports}\n{imports}\n{function}\n\n{goMainFunction}");
                string goOutputFile = Path.Join(_build, $"{name}");
                if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                {
                    goOutputFile = $"{goOutputFile}.dll";
                } else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                {
                    goOutputFile = $"{goOutputFile}.so";
                } else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                {
                    goOutputFile = $"{goOutputFile}.dylib";
                }

                ProcessStartInfo goInfo = new ProcessStartInfo
                {
                    FileName = "go",
                    Arguments = $"build -buildmode=c-shared -o {goOutputFile} {goFile}",
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };
                using (Process goProcess = Process.Start(goInfo))
                {
                    string goOutput = goProcess.StandardOutput.ReadToEnd();
                    string goError = goProcess.StandardError.ReadToEnd();
                    
                    Console.WriteLine(goOutput);
                    
                    goProcess.WaitForExit();

                    if (goProcess.ExitCode != 0)
                    {
                        Console.WriteLine($"Error: {goError}");
                    }
                }
                
                File.Delete(goFile);
                File.Delete(Path.Join(_build, $"{name}.h"));
                return goOutputFile;
            case "JAVA":
                string buildDir = Path.Join(_build, name);
                Directory.CreateDirectory(buildDir);

                string javaFile = Path.Join(buildDir, "VeneerTooth.java");
                string javaImports = """
                                     import org.graalvm.nativeimage.IsolateThread;
                                     import org.graalvm.nativeimage.c.function.CEntryPoint;
                                     """;
                string javaClassWrapper = "public final class VeneerTooth";
                File.WriteAllText(javaFile, $"{javaImports}\n{imports}\n{javaClassWrapper}{{{function}}}");

                // 1. Run javac relatively inside buildDir
                ProcessStartInfo javaInfo = new ProcessStartInfo
                {
                    FileName = "javac",
                    Arguments = "VeneerTooth.java",
                    WorkingDirectory = buildDir, // Run locally inside build directory
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                using (Process javaProcess = Process.Start(javaInfo))
                {
                    Console.WriteLine(javaProcess.StandardOutput.ReadToEnd());
                    string javaError = javaProcess.StandardError.ReadToEnd();
                    javaProcess.WaitForExit();
                    if (javaProcess.ExitCode != 0)
                    {
                        Console.WriteLine($"Error: {javaError}");
                        return default(string);
                    }
                }

                // 2. Run native-image using purely relative naming so no absolute paths leak into the binary
                ProcessStartInfo nativeImageInfo = new ProcessStartInfo
                {
                    FileName = "native-image",
                    Arguments = $"--shared -H:Name=VeneerTooth.class -cp .",
                    WorkingDirectory = buildDir, // Run locally inside build directory
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                using (Process nativeImageProcess = Process.Start(nativeImageInfo))
                {
                    Console.WriteLine(nativeImageProcess.StandardOutput.ReadToEnd());
                    string nativeImageError = nativeImageProcess.StandardError.ReadToEnd();
                    nativeImageProcess.WaitForExit();
                    if (nativeImageProcess.ExitCode != 0)
                    {
                        Console.WriteLine($"Error: {nativeImageError}");
                        return default(string);
                    }
                }

                string headerFile = Path.Join(buildDir, "VeneerTooth.class.h");
                if (!File.Exists(headerFile) || !File.ReadAllText(headerFile).Contains(functionName))
                {
                    Console.WriteLine($"Error: expected entry point '{functionName}' was not found in {headerFile}.");
                    return default(string);
                }

                string javaCFile = Path.Join(buildDir, "main.c");
                File.WriteAllText(javaCFile, cWrapper);

                string javaOutputFile = Path.Join(buildDir, name);   
                string javaArguments = "";

                // 3. Link using purely local filenames so the linker bakes relative relationships
                if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                {
                    javaOutputFile += ".dll";
                    javaArguments = $"-shared -o {name}.dll main.c VeneerTooth.class.dll -I.";
                }
                else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                {
                    javaOutputFile += ".so";
                    javaArguments = $"-shared -fPIC -o {name}.so main.c VeneerTooth.class.so -I. -Wl,-rpath,$ORIGIN";
                }
                else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                {
                    javaOutputFile += ".dylib";
                    javaArguments = $"-dynamiclib -o {name}.dylib main.c VeneerTooth.class.dylib -I. -Wl,-rpath,@loader_path";
                }

                ProcessStartInfo javaCStartInfo = new ProcessStartInfo
                {
                    FileName = "gcc",
                    Arguments = javaArguments,
                    WorkingDirectory = buildDir, // Run locally inside build directory
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                bool gccSucceeded;
                using (Process javaCProcess = Process.Start(javaCStartInfo))
                {
                    Console.WriteLine(javaCProcess.StandardOutput.ReadToEnd());
                    string javaCError = javaCProcess.StandardError.ReadToEnd();
                    javaCProcess.WaitForExit();
                    gccSucceeded = javaCProcess.ExitCode == 0;
                    if (!gccSucceeded) Console.WriteLine($"Error: {javaCError}");
                }

                if (gccSucceeded)
                {
                    // Safe to delete compile-time artifacts using precise paths
                    File.Delete(javaFile);
                    File.Delete(Path.Join(buildDir, "VeneerTooth.class"));
                    File.Delete(javaCFile);
                    File.Delete(headerFile);
                    File.Delete(Path.Join(buildDir, "graal_isolate.h"));
                    File.Delete(Path.Join(buildDir, "graal_isolate_dynamic.h"));
                    File.Delete(Path.Join(buildDir, "VeneerTooth.class_dynamic.h"));
                }

                return gccSucceeded ? javaOutputFile : default(string);
            default:
                return default(string);
        }
    }
    
    // Generate c# code for outliers out of languages
    private string GenerateOutlierCode(string language, string function, string parameters, string returnType, string name)
    {
        string imports = _configs.ContainsKey(language) ? _configs[language].imports : "";
        bool isVoid = returnType.Trim().ToLower() == "void";
        string leadingString = isVoid ? "" : $"return ({returnType})";

        switch (language)
        {
            case "JAVASCRIPT":
                string embeddedString = isVoid ? "" : $"<{returnType}>";
                List<string> jsParamsToks = Lexer
                    .LexText(parameters)
                    .Where(n => n.Type == Tokens.TokenType.Identifier)
                    .Select(n => n.Value)
                    .Select(n => $"(object) {n}")
                    .ToList();
                string jsParams = string.Join(", ", jsParamsToks);
                
                StringBuilder jsBody = new StringBuilder();
                jsBody.AppendLine($"{returnType} {name} ({parameters}) {{");
                jsBody.AppendLine($"{leadingString} JavascriptManager.Run{embeddedString}({JsonSerializer.Serialize(function)}, {jsParams});");
                jsBody.AppendLine("}");
                return jsBody.ToString();
            case "TYPESCRIPT":
                string uuidName = Guid.NewGuid().ToString();
                string typescriptFile = Path.Join(_build, $"{uuidName}.ts");
                string javascriptFile = Path.Join(_build, $"{uuidName}.js");
                File.WriteAllText(typescriptFile, function);

                ProcessStartInfo typescriptInfo = new ProcessStartInfo
                {
                    FileName = "tsc",
                    Arguments = $"{typescriptFile}",
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                using (Process typescriptProcess = Process.Start(typescriptInfo))
                {
                    string typescriptOutput = typescriptProcess.StandardOutput.ReadToEnd();
                    string typescriptError = typescriptProcess.StandardError.ReadToEnd();
                    
                    Console.WriteLine(typescriptOutput);
                    
                    typescriptProcess.WaitForExit();

                    if (typescriptProcess.ExitCode != 0)
                    {
                        Console.WriteLine($"Error: {typescriptError}");
                    }
                }

                string output = File.ReadAllText(javascriptFile);
                File.Delete(javascriptFile);
                File.Delete(typescriptFile);
                return GenerateOutlierCode("JAVASCRIPT", output, parameters, returnType, name);
            case "PYTHON":
                string pythonBody = $"{imports}\n{function}";
                List<string> pyParamToks = Lexer
                    .LexText(parameters)
                    .Where(n => n.Type == Tokens.TokenType.Identifier)
                    .Select(n => n.Value)
                    .Select(n => $"(object) {n}")
                    .ToList();
                string pyParams = string.Join(", ", pyParamToks);
                string pyReturn = returnType == "void" ? "object" : returnType;
                StringBuilder pyBody = new StringBuilder();
                pyBody.AppendLine($"{returnType} {name}({parameters}) {{");
                pyBody.AppendLine($"{leadingString}PythonManager.Instance.Execute<{pyReturn}>({JsonSerializer.Serialize(pythonBody)}, {JsonSerializer.Serialize(name)}, {pyParams});");
                pyBody.AppendLine("}");
                return pyBody.ToString();
            default:
                return default(string);
        }
    }

    // Translates: Foregin Code Block to c# code, handling the interop layer
    private string ParseChip(string language, string parameters, string body, string returnType, string functionName)
    {
        language = language.ToUpper().TrimStart('\"').TrimEnd('\"');
        
        string foreignFunction = CreateForeignFunction(parameters, language, body, returnType, functionName);
        Console.WriteLine($"Foreign function: {foreignFunction}");

        List<string> baseToks = toothModifiers
                .Select(n => n.Value)
                .ToList();
        
        if (language == "CSHARP")
        {
            toothModifiers.Clear();
            return $"{string.Join(" ", baseToks)} {foreignFunction}";
        }

        string cWrapper = "";
        string entryPoint = "";
        if (language == "JAVA")
        {
            entryPoint = $"{functionName}X";
            List<string> paramToks = Lexer
                .LexText(parameters)
                .Where(n => n.Type == Tokens.TokenType.Identifier)
                .Select(n => n.Value)
                .ToList();
            string leadingBodyString = returnType.Trim().ToLower() == "void" ? "" : "return ";
            string cWrapperBody = $"""
                                  ensure_isolate();
                                  {leadingBodyString}{functionName}X(thread, {string.Join(", ", paramToks)});
                                  """;
            cWrapper = $$"""
                         #include "VeneerTooth.class.h"
                         #include <stdio.h>
                         static graal_isolatethread_t *thread = NULL;
                         
                         static void ensure_isolate(void) {
                             if (thread == NULL) {
                                 graal_isolate_t *isolate = NULL;
                                 graal_create_isolate(NULL, &isolate, &thread);
                             }
                         }
                         {{CreateForeignFunction(parameters, "C", cWrapperBody, returnType, functionName)}}
                         """;
        }

        string libraryFile = CompileFunction(foreignFunction, language, cWrapper, entryPoint);
        if (File.Exists(libraryFile))
        {
            List<string> compiledToks = toothModifiers
                .Where(n => n.Value != "static")
                .Select(n => n.Value)
                .ToList();
            toothModifiers.Clear();
            return $"[DllImport(\"{Path.GetRelativePath(_build, libraryFile)}\")]" +
                   $"\n{string.Join(" ", compiledToks)} static extern {returnType} {functionName}({parameters});\n";
        }
        
        toothModifiers.Clear();
        return $"{string.Join(" ", baseToks)} {GenerateOutlierCode(language, foreignFunction, parameters, returnType, functionName)}";
    }

    // Translates: tooth<[RETURN_TYPE]> [IDENTIFIER] ([ARGS]) language ("[LANG]") => [TAG] \n [CODE] \n [TAG]
    private string ParseTooth()
    {
        Consume(Tokens.TokenType.Tooth, "Expected 'tooth' keyword.");
        Consume(Tokens.TokenType.LessThan, "Expected '<' following 'tooth'.");
        
        string returnType = ParseReturnType();
        
        Consume(Tokens.TokenType.GreaterThan, "Expected '>' closing tooth return type.");
        
        var nameTok = Consume(Tokens.TokenType.Identifier, "Expected identifier for tooth name.");
        string toothName = nameTok.Value;

        Consume(Tokens.TokenType.LeftParen, "Expected '(' after tooth identifier.");
        var paramsSb = new StringBuilder();
        while (Peek().Type != Tokens.TokenType.RightParen && Peek().Type != Tokens.TokenType.EndOfFile)
        {
            paramsSb.Append(Peek().Value + " ");
            _index++;
        }
        Consume(Tokens.TokenType.RightParen, "Expected ')' closing tooth parameters.");

        Consume(Tokens.TokenType.Language, "Expected 'language' property constraint.");
        Consume(Tokens.TokenType.LeftParen, "Expected '(' framing target platform string.");
        var langTok = Consume(Tokens.TokenType.StringLiteral, "Expected literal string definition for language target.");
        Consume(Tokens.TokenType.RightParen, "Expected ')' framing target platform string.");

        // CONSUME NEW ARROW HEREDOC STRUCTURE
        Consume(Tokens.TokenType.Arrow, "Expected '=>' boundary operator to open foreign code zone.");
        var tagTok = Consume(Tokens.TokenType.Identifier, "Expected block identifier bounding tag.");
        var bodyTok = Consume(Tokens.TokenType.ForeignCodeBlock, "Expected raw foreign content packet data.");

        var toothBodySb = new StringBuilder();

        // TODO: Generate c# codeblock from foreign code block
        toothBodySb.Append(ParseChip(
            langTok.Value, 
            paramsSb.ToString().Trim(), 
            bodyTok.Value, 
            returnType, 
            toothName)
        );
        
        var sb = new StringBuilder();
        if (toothBodySb.Length > 0)
        {
            sb.Append(" " + toothBodySb);
        }
        else
        {
            sb.AppendLine($"\tpublic static {returnType} {toothName}({paramsSb.ToString().Trim()})");
            sb.AppendLine("\t{");
            sb.AppendLine("\t}");
        }

        
        return sb.ToString();
    }

    private string ParseBlock()
    {
        Consume(Tokens.TokenType.LeftBrace, "Expected '{' code block initializer.");
        var sb = new StringBuilder("{\n\t\t");
        int braceScope = 1;

        while (braceScope > 0 && Peek().Type != Tokens.TokenType.EndOfFile)
        {
            var tok = Peek();
            if (tok.Type == Tokens.TokenType.LeftBrace) braceScope++;
            if (tok.Type == Tokens.TokenType.RightBrace) braceScope--;

            _index++;
            if (braceScope == 0)
            {
                sb.AppendLine("}");
                break;
            }

            sb.Append(EmitTokenFormatting(tok));
        }
        return sb.ToString();
    }

    // Handles code formatting aesthetics so target C# code compiles perfectly
    private string EmitTokenFormatting(Tokens.Token token)
    {
        if (token == null) return "";
        
        switch (token.Type)
        {
            case Tokens.TokenType.SemiColon:
                return ";\n\t\t";
            case Tokens.TokenType.LeftBrace:
                return "{\n\t\t";
            case Tokens.TokenType.RightBrace:
                return "}\n\t\t";
            case Tokens.TokenType.For:
            case Tokens.TokenType.While:
            case Tokens.TokenType.If:
            case Tokens.TokenType.Else:
            case Tokens.TokenType.Return:
            case Tokens.TokenType.Int:
            case Tokens.TokenType.Float:
            case Tokens.TokenType.Double:
            case Tokens.TokenType.Bool:
            case Tokens.TokenType.Char:
            case Tokens.TokenType.Void:
            case Tokens.TokenType.String:
            case Tokens.TokenType.New:
            case Tokens.TokenType.Class:
            case Tokens.TokenType.Public:
            case Tokens.TokenType.Private:
            case Tokens.TokenType.Protected:
            case Tokens.TokenType.Internal:
            case Tokens.TokenType.Static:
            case Tokens.TokenType.ReadOnly:
            case Tokens.TokenType.Const:
            case Tokens.TokenType.Async:
            case Tokens.TokenType.Virtual:
            case Tokens.TokenType.Override:
            case Tokens.TokenType.Sealed:
                return token.Value + " ";
            case Tokens.TokenType.Assign:
            case Tokens.TokenType.Plus:
            case Tokens.TokenType.Minus:
            case Tokens.TokenType.Star:
            case Tokens.TokenType.Slash:
            case Tokens.TokenType.EqualEqual:
            case Tokens.TokenType.NotEqual:
            case Tokens.TokenType.LessThan:
            case Tokens.TokenType.LessEqual:
            case Tokens.TokenType.GreaterThan:
            case Tokens.TokenType.GreaterEqual:
            case Tokens.TokenType.AmpAmp:
            case Tokens.TokenType.PipePipe:
                return " " + token.Value + " ";
            case Tokens.TokenType.Comma:
                return ", ";
            default:
                return token.Value;
        }
    }
}