using System;
using System.Collections.Generic;
using System.Text;

namespace Veneer;

public class Transpiler
{
    private readonly List<Tokens.Token> _tokens;
    private int _index = 0;

    public Transpiler(List<Tokens.Token> tokens)
    {
        _tokens = tokens;
    }

    // Helper to look ahead without consuming
    private Tokens.Token Peek(int offset = 0)
    {
        if (_index + offset >= _tokens.Count) 
            return new Tokens.Token(Tokens.TokenType.EndOfFile, "");
        return _tokens[_index + offset];
    }

    // Guard & consume an expected token type
    private Tokens.Token Consume(Tokens.TokenType type, string errorMessage)
    {
        var token = Peek();
        if (token.Type != type) 
            throw new Exception($"[Transpile Error] {errorMessage} Found '{token.Value}' instead at token position {_index}.");
        _index++;
        return token;
    }

    public string Transpile()
    {
        var sb = new StringBuilder();
        
        // Phase 4 Blueprint: Generate a high-performance C# template class
        sb.AppendLine("//---------------------------------------------------------");
        sb.AppendLine("// <auto-generated> Transpiled from Veneer Source </auto-generated>");
        sb.AppendLine("//---------------------------------------------------------");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace VeneerRuntime;");
        sb.AppendLine();
        sb.AppendLine("public static class Program");
        sb.AppendLine("{");

        // Parse global-level constructs until we hit the end of the file
        while (Peek().Type != Tokens.TokenType.EndOfFile)
        {
            sb.Append(ParseTopLevelStatement());
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private string ParseTopLevelStatement()
    {
        var token = Peek();

        if (token.Type == Tokens.TokenType.Function)
        {
            return ParseFunction();
        }
        if (token.Type == Tokens.TokenType.Tooth)
        {
            return ParseTooth();
        }

        // Allow classes or other global expressions to fall back gracefully
        _index++;
        return EmitTokenFormatting(token);
    }

    // Translates: func<[RETURN_TYPE]> [IDENTIFIER] ([ARGS]) { ... }
    private string ParseFunction()
    {
        Consume(Tokens.TokenType.Function, "Expected 'func' keyword.");
        Consume(Tokens.TokenType.LessThan, "Expected '<' following 'func'.");
        
        var returnTypeTok = Peek();
        _index++; 
        string returnType = returnTypeTok.Value;
        
        Consume(Tokens.TokenType.GreaterThan, "Expected '>' closing return type.");
        
        var nameTok = Consume(Tokens.TokenType.Identifier, "Expected identifier for function name.");
        string funcName = nameTok.Value;

        // Auto-map lower-case 'main' to C#'s entry point format
        if (funcName == "main") funcName = "Main";

        Consume(Tokens.TokenType.LeftParen, "Expected '(' after function identifier.");
        
        var paramsSb = new StringBuilder();
        while (Peek().Type != Tokens.TokenType.RightParen && Peek().Type != Tokens.TokenType.EndOfFile)
        {
            paramsSb.Append(Peek().Value + " ");
            _index++;
        }
        Consume(Tokens.TokenType.RightParen, "Expected ')' closing parameters.");

        // Grab internal function block execution loops
        string blockBody = ParseBlock();

        return $"\tpublic static {returnType} {funcName}({paramsSb.ToString().Trim()})\n\t{blockBody}\n";
    }

    // Translates: tooth<[RETURN_TYPE]> [IDENTIFIER] ([ARGS]) language ("[LANG]") => [TAG] \n [CODE] \n [TAG]
    private string ParseTooth()
    {
        Consume(Tokens.TokenType.Tooth, "Expected 'tooth' keyword.");
        Consume(Tokens.TokenType.LessThan, "Expected '<' following 'tooth'.");
        
        var returnTypeTok = Peek();
        _index++;
        string returnType = returnTypeTok.Value;
        
        Consume(Tokens.TokenType.GreaterThan, "Expected '>' closing tooth return type.");
        
        var nameTok = Consume(Tokens.TokenType.Identifier, "Expected identifier for tooth name.");
        string toothName = nameTok.Value;

        Consume(Tokens.TokenType.LeftParen, "Expected '(' after tooth identifier.");
        var paramsSb = new StringBuilder();
        while (Peek().Type != Tokens.TokenType.RightParen && Peek().Type != Tokens.TokenType.EndOfFile)
        {
            paramsSb.Append(Peek().Value + " ");
            _index++;
        }
        Consume(Tokens.TokenType.RightParen, "Expected ')' closing tooth parameters.");

        Consume(Tokens.TokenType.Language, "Expected 'language' property constraint.");
        Consume(Tokens.TokenType.LeftParen, "Expected '(' framing target platform string.");
        var langTok = Consume(Tokens.TokenType.StringLiteral, "Expected literal string definition for language target.");
        Consume(Tokens.TokenType.RightParen, "Expected ')' framing target platform string.");

        // CONSUME NEW ARROW HEREDOC STRUCTURE
        Consume(Tokens.TokenType.Arrow, "Expected '=>' boundary operator to open foreign code zone.");
        var tagTok = Consume(Tokens.TokenType.Identifier, "Expected block identifier bounding tag.");
        var bodyTok = Consume(Tokens.TokenType.ForeignCodeBlock, "Expected raw foreign content packet data.");

        var toothBodySb = new StringBuilder();
        toothBodySb.AppendLine($"\t\t// [Tooth Engine Gateway]: Foreign Code Block Extraction Below");
        toothBodySb.AppendLine($"\t\t// Target Sub-Ecosystem: {langTok.Value}");
        toothBodySb.AppendLine($"\t\t// Identifier Envelope Guard: {tagTok.Value}");

        // Split up the captured multiline block string and display safely as code comments
        string[] lines = bodyTok.Value.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
        foreach (var line in lines)
        {
            if (!string.IsNullOrWhiteSpace(line))
            {
                toothBodySb.AppendLine($"\t\t// {line}");
            }
        }

        string defaultFallback = returnType == "void" ? "" : $"return default({returnType});";
        
        var sb = new StringBuilder();
        sb.AppendLine($"\tpublic static {returnType} {toothName}({paramsSb.ToString().Trim()})");
        sb.AppendLine("\t{");
        sb.Append(toothBodySb.ToString());
        sb.AppendLine($"\t\tthrow new NotImplementedException(\"Veneer Marshalling Engine for {langTok.Value} is in prototype stages.\");");
        if (!string.IsNullOrEmpty(defaultFallback)) sb.AppendLine($"\t\t{defaultFallback}");
        sb.AppendLine("\t}");
        
        return sb.ToString();
    }

    private string ParseBlock()
    {
        Consume(Tokens.TokenType.LeftBrace, "Expected '{' code block initializer.");
        var sb = new StringBuilder("{\n\t\t");
        int braceScope = 1;

        while (braceScope > 0 && Peek().Type != Tokens.TokenType.EndOfFile)
        {
            var tok = Peek();
            if (tok.Type == Tokens.TokenType.LeftBrace) braceScope++;
            if (tok.Type == Tokens.TokenType.RightBrace) braceScope--;

            _index++;
            if (braceScope == 0)
            {
                sb.AppendLine("}");
                break;
            }

            sb.Append(EmitTokenFormatting(tok));
        }
        return sb.ToString();
    }

    // Handles code formatting aesthetics so target C# code compiles perfectly
    private string EmitTokenFormatting(Tokens.Token token)
    {
        if (token == null) return "";
        
        switch (token.Type)
        {
            case Tokens.TokenType.SemiColon:
                return ";\n\t\t";
            case Tokens.TokenType.LeftBrace:
                return "{\n\t\t";
            case Tokens.TokenType.RightBrace:
                return "}\n\t\t";
            case Tokens.TokenType.For:
            case Tokens.TokenType.While:
            case Tokens.TokenType.If:
            case Tokens.TokenType.Else:
            case Tokens.TokenType.Return:
            case Tokens.TokenType.Int:
            case Tokens.TokenType.Float:
            case Tokens.TokenType.Bool:
            case Tokens.TokenType.Char:
            case Tokens.TokenType.Void:
            case Tokens.TokenType.String:
            case Tokens.TokenType.New:
            case Tokens.TokenType.Class:
            case Tokens.TokenType.Public:
            case Tokens.TokenType.Private:
            case Tokens.TokenType.Protected:
            case Tokens.TokenType.Internal:
                return token.Value + " ";
            case Tokens.TokenType.Assign:
            case Tokens.TokenType.Plus:
            case Tokens.TokenType.Minus:
            case Tokens.TokenType.Star:
            case Tokens.TokenType.Slash:
            case Tokens.TokenType.EqualEqual:
            case Tokens.TokenType.NotEqual:
            case Tokens.TokenType.LessThan:
            case Tokens.TokenType.LessEqual:
            case Tokens.TokenType.GreaterThan:
            case Tokens.TokenType.GreaterEqual:
            case Tokens.TokenType.AmpAmp:
            case Tokens.TokenType.PipePipe:
                return " " + token.Value + " ";
            case Tokens.TokenType.Comma:
                return ", ";
            default:
                return token.Value;
        }
    }
}